image: oracle/graalvm-ce:latest

variables:
  MAVEN_OPTS: "-Xms128m -Xmx512m"

stages:
  - resource_check
  - compile
  - test
  - native

resource_check:
  stage: resource_check
  script: "java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'"

compile:
  stage: compile
  script: "./mvnw install -DskipTests -B -V"

test:
  stage: test
  script: "./mvnw test -B -V -Dsurefire.useFile=false -Dprofile=test"

#Disabled for now, locally uses a lot of resources to generate a container-friendly native image.
#native:
#  stage: native
#  script: "./mvnw package -Pnative -Dsurefire.useFile=false -DskipTests -Dquarkus.native.container-build=true"